version: '3.8'

services:
  web:
    build: .
    command: bash -c "flask db upgrade -d core/migrations/ && gunicorn -c gunicorn_config.py core.server:app"
    ports:
      - "7755:7755"
    environment:
      FLASK_APP: core/server.py
